# Generated by Django 5.1 on 2024-08-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dados1_sobremim1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dados',
        ),
        migrations.DeleteModel(
            name='sobremim',
        ),
    ]
