# Generated by Django 5.1 on 2024-08-24 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_foto1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='foto',
        ),
    ]
